name: Publish

on:
  release:
    types: 
        - published

jobs:
  publish:
    name: Publish to github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'app'
            name: 'crypto'
            compress: 'true'
            dest: 'dist'
      - name: Upload to release
        uses: skx/github-action-publish-binaries@release-0.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"
